version: '3.1'
services:
  db: 
    image: mysql
    container_name: api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: api_typescript
    ports:
      - "3306:3306"
    volumes:
      - api_mysql_data:/var/lib/mysql

volumes:
  api_mysql_data: